---
- hosts: '{{ local_fw  }}'
  connection: local
  gather_facts: False

  roles:
    - role: paloaltonetworks.paloaltonetworks

  vars:
    - local_fw : '{{ local_fw  }}'
      remote_fw: '{{ remote_fw }}'
      local_tunnel_interface: '{{ local_tunnel_interface }}'
      local_tunnel_ip: '{{ local_tunnel_ip }}'
      remote_tunnel_interface: '{{ remote_tunnel_interface }}'
      remote_tunnel_ip: '{{ remote_tunnel_ip }}'

  tasks:
    - name: debug
      debug: 
        msg: "{{ USE1_TRANSIT_AZ1_FW1_PROD_TunnelInterface }}"
      tags:
        - debug

    - name: debug
      debug: 
        msg: "{{ local_tunnel_interface }}"
      tags:
        - debug

