---
- hosts: '{{ local_fw  }}'
  connection: local
  gather_facts: False

  roles:
    - role: paloaltonetworks.paloaltonetworks

  vars:
    - local_fw : '{{ local_fw  }}'
      remote_fw: '{{ remote_fw }}'
      local_tunnel_interface: '{{ local_tunnel_interface }}'
      local_tunnel_ip: '{{ local_tunnel_ip }}'
      remote_tunnel_interface: '{{ remote_tunnel_interface }}'
      remote_tunnel_ip: '{{ remote_tunnel_ip }}'

  tasks:
    - name: debug
      debug: 
        msg: "{{ USE1_TRANSIT_AZ1_FW1_PROD_TunnelInterface }}"
      tags:
        - debug

    - name: debug
      debug: 
        msg: "{{ local_tunnel_interface }}"
      tags:
        - debug

    - name: Create IKE Gateway on FW1
      panos_ike_gateway:
        username: '{{ username }}'
        password: '{{ password }}'
        ip_address: '{{ panorama }}'
        template: '{{ template }}'
        version: 'ikev2'        
        state: 'present' 
        name: 'IKE_{{ item.name }}'
        interface: '{{ untrust_int }}'
        enable_passive_mode: 'no'
        local_id_type: 'ipaddr'
        local_id_value:  '{{ untrust_ip_public }}'
        peer_id_type: 'ipaddr'
        peer_id_value: '{{ item.untrust_ip_public }}'
        pre_shared_key: '{{ psk }}'
        peer_ip_value: '{{ item.untrust_ip_public }}'
        ikev1_crypto_profile: 'ICP_DH-G5_AUTH-SHA256_EN-AES256'
        ikev2_crypto_profile: 'ICP_DH-G5_AUTH-SHA256_EN-AES256'
        commit: False 
      with_items:
        - "{{ hostvars[remote_fw] }}"
      tags:
        - vpn

    - name: Creat VPC Security Zone FW1
      panos_zone:
        username: '{{ username }}'
        password: '{{ password }}'
        ip_address: '{{ panorama }}'
        template: '{{ template }}'  
        zone: '{{ item.name }}'
        mode: 'layer3'
      with_items:
        - "{{ hostvars[remote_fw] }}"
      tags:
        - vpn

    - name: Create tunnel IP interfaces for FW1
      panos_tunnel:
        username: '{{ username }}'
        password: '{{ password }}'
        ip_address: '{{ panorama }}'
        template: '{{ template }}'
        if_name: '{{ local_tunnel_interface }}'
        ip: '{{ local_tunnel_ip }}/30'
        vr_name: '{{ routing_instance }}'
        zone_name: "{{ item.name }}"
        commit: False
      with_items:
        - "{{ hostvars[remote_fw] }}"
      tags:
        - vpn

    - name: Create IPSec Tunnel for FW1
      panos_ipsec_tunnel:
        username: '{{ username }}'
        password: '{{ password }}'
        ip_address: '{{ panorama }}'
        template: '{{ template }}'
        name: 'IPS_{{ item.name }}'
        tunnel_interface: '{{ local_tunnel_interface }}'
        ak_ike_gateway: 'IKE_{{ item.name }}'
        ak_ipsec_crypto_profile: 'IPCP_EN-AES256_AU-SHA256_DH-G5'
        state: 'present'
        commit: False   
      with_items:
        - "{{ hostvars[remote_fw] }}"
      tags:
        - vpn
